---
# install PromOps
- name: Create directory to hold templates
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}/{{ item.name }}"
  with_items:
    - "{{ promops_templates }}"
  tags:
    - build_promops_tmpl

- name: Build {{ item.name }} templates
  template:
    src: "{{ item.0.name }}/{{ item.1 }}"
    dest: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}/{{ item.0.name }}/{{ item.1[:-3] }}"
  with_subelements:
    - "{{ promops_templates }}"
    - tmpl
  tags:
    - build_promops_tmpl

- name: Get current namespaces
  command: kubectl get namespaces -o go-template={% raw %}'{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'{% endraw %}
  register: k8s_namespaces
  changed_when: false

- name: Create namespace
  command: kubectl create namespace {{ promops_deploy.namespace }}
  when: promops_deploy.namespace not in k8s_namespaces.stdout_lines

- name: Deploy Prometheus Operator
  command: kubectl -n {{ promops_deploy.namespace }} apply -f prometheus-operator/
  args:
    chdir: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}"
  ignore_errors: true

- name: Wait for Custom Resource Definitions to be available
  shell: kubectl get customresourcedefinition {{ item }}.monitoring.coreos.com > /dev/null 2>&1
  register: crd_check
  until: crd_check.rc == 0
  retries: 30
  delay: 1
  with_items:
    - servicemonitors
    - prometheuses
    - alertmanagers
  changed_when: false

- name: Deploy primary components
  command: kubectl -n {{ promops_deploy.namespace }} apply -f {{ item }}
  args:
    chdir: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}"
  ignore_errors: true
  with_items:
    - "{{ promops_deploy.components }}"

- name: Deploy Prometheus roles and bindings
  command: kubectl apply -f prometheus-roles-bindings/
  args:
    chdir: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}"
  ignore_errors: true

- name: Deploy service monitors
  command: kubectl -n {{ promops_deploy.namespace }} apply -f service-monitors/prometheus-k8s-service-monitor-{{ item }}.yaml
  args:
    chdir: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}"
  with_items:
    - "{{ promops_deploy.service_monitors }}"

- name: Deploy Alertmanager
  command: kubectl -n {{ promops_deploy.namespace }} apply -f {{ item }}
  args:
    chdir: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}"
  ignore_errors: true
  with_items:
    - alertmanager
  when: promops_deploy.include_alertmanager | default(false) | bool

- name: Setup services to monitor Kubernetes components
  command: kubectl apply -f k8s/
  args:
    chdir: "{{ ansible_env.HOME }}/promops_tmpl_{{ promops_deploy.name }}"
    ignore_errors: true
  when: promops_deploy.monitor_k8s | default(false) | bool
