apiVersion: v1
kind: Service
metadata:
  name: metrics
  labels:
    {{ promops_deploy.name }}-app: metrics
spec:
  selector:
    {{ promops_deploy.name }}-app: metrics
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
